"""
Analysis Report persistence models for FinSentry AI (Phase 2G - Live Processing).
"""

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ReportSectionModel(BaseModel):
    """Sub-section within an analytical research report."""

    title: str = Field(..., description="Section title")
    content: str = Field(..., description="Analytical content in markdown format")
    key_findings: List[str] = Field(default_factory=list, description="Bullet key findings")


class AnalysisReportModel(BaseModel):
    """
    MongoDB persistence document for an analytical research report generated by Live Processing.
    """

    id: Optional[str] = Field(None, alias="_id", description="MongoDB ObjectId string")
    report_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique UUID for the generated analysis report",
    )
    session_id: str = Field(..., description="ID of the research session this report belongs to")
    user_id: str = Field(..., description="ID of the owning user")
    report_title: str = Field(
        default="Comprehensive Financial Analysis Report",
        description="Title of the research report",
    )
    executive_summary: str = Field(
        default="",
        description="Executive summary synthesizing all multi-agent findings",
    )
    risk_score: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Composite financial risk score (0=safe, 100=extreme risk)",
    )
    sections: List[ReportSectionModel] = Field(
        default_factory=list,
        description="Structured sections of the report",
    )
    extracted_metrics: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Key financial metrics extracted during the live analysis pipeline",
    )
    red_flags: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Forensic red flags and risk anomalies detected",
    )
    recommendations: List[str] = Field(
        default_factory=list,
        description="Strategic recommendations from synthesis agent",
    )
    status: str = Field(
        default="COMPLETED",
        description="Status of the report (e.g. COMPLETED, PROCESSING, FAILED)",
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        """Convert model to MongoDB document dict."""
        data = self.model_dump(by_alias=False)
        if "id" in data and data["id"] is None:
            data.pop("id", None)
        return data

    @classmethod
    def from_mongo(cls, doc: Dict[str, Any]) -> "AnalysisReportModel":
        """Reconstruct model from MongoDB document."""
        if not doc:
            raise ValueError("Empty document cannot be converted to AnalysisReportModel")
        doc_copy = dict(doc)
        if "_id" in doc_copy:
            doc_copy["_id"] = str(doc_copy["_id"])
        return cls(**doc_copy)
